// 1 задание 
let a = 10;
alert (a);
a = 20;
alert (a);

// 2 задание
let releaseYear = 2007;
alert(releaseYear);

// 3 задание
let name = 'Брендан Эйх';
alert('name');

// 4 задание 
let namber1 = 10;
let namber2 = 2;
let sum = namber1 + namber2;
let difference = namber1 - namber2;
let product = namber1 * namber2;
let quotient = namber1 / namber2;
alert('Сумма: ' + sum);
alert('Разность: ' + difference);
alert('Произведение: ' + product);
alert('Частное: ' + quotient);

// 5 Задания
let result = 2 ** 5;
alert(result);

// 6 Задание
let n = 9;
let b = 2;
let remainder = n % b;
alert(remainder);

// 7 Задание 
let num = 1;
num += 5;
num -= 3;
num *= 7;
num /= 3;
num++;
num--;
alert(num);

// 8 Задание 
let age = prompt('Сколько вам лет?');
alert(age);

// 9 Задание 
const user = {
  name: "Анна",
  age: 30,
  isAdmin: true
};

// 10 Задание 
let info = prompt('Как тебя зовут?')
alert(`Привет, ${info}!`);




