// 1 Задание
// let pasword = 'пароль';
// let enter = prompt ('Введите пароль');
// if (enter === pasword) {
   // alert ('Пароль введен верно');
// } else {
   // alert ('Пароль введен неправильно');
//}

// 2 Задание
// let c = 10 ;
// if (c > 0 && c < 10) {
   // console.log ('Верно');
//} else {
  //  console.log ('Неверно');
//}

// 3 Задание 
// let d = 210;
// let e = 12;
// if (d > 100 || e > 100) {
   // console.log ('Верно');
// } else {
   // console.log ('Неверно');
// }

// 4 Задание
// let y = '3';
// let s = '2';
// alert (+y + +s);

// 5 Задание 
// let monthNumber = 12;
// switch (monthNumber) {
   // case 12:
    //case 1:
    //case 2:
    //console.log ('Зима');    
      //  break;
    //case 3:
    //case 4:
    //case 5: 
    //console.log ('Осень');
      //  break;
    //case 6:
    //case 7:
    //case 8:
    //console.log ('Лето');                
      //  break;
    //case 9:
    //case 10:
    //case 11:
    //console.log ('Осень');
      //  break;                
//}