// 1 задание
//for (let i = 0; i < 2; i++) {
   // console.log('Привет'); 
///}

// 2 задание
//for (let i = 1; i <= 5; i++) {
    //console.log (i);
//}

// 3 задание 
//for (let i = 7; i <= 22; i++) {
   // console.log (i);
//}

// 4 задание
//const obj = {
  //  'Коля': '200',
   // 'Вася': '300',
   // 'Петя': '400'
//};
//for(let name in obj) {
   // console.log (`${name}-зарплата ${obj[name]}-долларов`)
//}

// 5 задание
//let n = 1000;
//let num = 0;
//while (n > 50){
   // n /= 2;
   // num++;
//}
//consjle.log (`Финальноу число ${n}`);
//console.log (`Количество итераций ${num}`)

// 6 задание
//const fristFriday = 3;
//const daysinMonth = 31;

//for (let day = fristFriday; day <= daysinMonth; day += 7){
    //console.log(`Сеодня пятница, ${day}-е число. Нужно подготовичть отчет.`)
//}